script: git checkout develop && make test-app-ci
deploy:
  provider: heroku
  api_key:
    secure: C8LpMDweq9KI98zs/ni4hSEPbDA1jzbqGQnNCHtocrJTStNRXYxp4ekNV3aPyVqFrimdOfK1q8ooE+r9jYKWCFV4zrAOYFRJJUuQ5UZhzsDf/GL8yJpYQYAGwZ4W9TJHKggjhTxrFl1g7/PvSN4727hcF2sEjbl8Wca8hm7kM8g=
  app: anbu-presentation-func01
  on:
    repo: thyms/anbu-presentation
    branch: develop
