script: git checkout develop && make test-app-ci
deploy:
  provider: heroku
  api_key:
    secure: iobubcgx1dRN17CNYB38N12QP8ukxqVpH/sd7WelCPWxEFknYn9KRzczKDedOUiwsApovBDGW/4JMdO+uHNRktkRqjmV2vdTpLC1SYUHIwMGzG+B95NWIDaXU/XyJS2NzWb9caJk/eWvAaQ1b3WzqksaTDcGgQYur1hARD4nGDg=
  app: anbu-presentation-func01
  on:
    repo: thyms/anbu-presentation
    branch: develop
