script: git checkout develop && make test-app-ci
deploy:
  provider: heroku
  api_key:
    secure: RXbyn4GddCxAM2ZXHEzEn7Qn4pfOFiVvBnAqmsvmxgfoK8+4vL8VjgGPDAXJGHNVpYBCXbqfZ8auzUFkcPS9r6Lc2JuWEvkJbiJ5xYckruAGhKNkXi4bTigdrClDmH7Xor1FmjCrirruS12Uyortb5UZqePkn6IXN4GN9m0engs=
  app:
    develop: anbu-presentation-func01
